services:
  - type: web
    name: habitick-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
